const {test}=require('node:test');const assert=require('node:assert/strict');const S=require('../team-sharing.js').TeamSharing;
function setup(){let s=S.migrate({version:2,org:{id:'org-qa'},units:[{id:'branch',parentId:'org'},{id:'team',parentId:'branch'},{id:'other',parentId:'org'}],members:[],step:2});s.members.push({id:'owner',accountId:S.accounts[0].id,email:S.accounts[0].email,access:'Owner',role:'Manager',unitId:'org',scopes:[{unitId:'branch',includeSubUnits:true}]});S.consent(s,s.members[0]);return s;}
function invite(s,email=S.accounts[1].email){const i={id:crypto.randomUUID(),email,organizationId:s.org.id,invitedBy:S.accounts[0].id,status:'pending',unitId:'team',access:'Member',role:'Agent',scopes:[],expiresAt:new Date(Date.now()+86400000).toISOString()};s.invites.push(i);return i;}
function accept(s,i){s.currentAccountId=S.accountId(i.email);return S.accept(s,i.id);}
function view(s){s.currentAccountId=S.accounts[0].id;return S.visible(s);}
test('pending has no membership or business; authenticated invitee required',()=>{let s=setup(),i=invite(s);assert.equal(view(s).length,0);assert.throws(()=>S.accept(s,i.id));assert.equal(s.members.length,1);});
test('accept is idempotent, shares historical and new records without copying',()=>{let s=setup(),i=invite(s),before=s.business;const m=accept(s,i);S.accept(s,i.id);assert.equal(s.members.length,2);assert.equal(s.grants.length,2);assert.equal(s.business,before);assert.equal(view(s).length,3);s.business.push({id:'new',accountId:m.accountId,type:'lead',shareable:true});assert.equal(view(s).length,4);assert.ok(S.grant(s,m).acceptedAt);});
test('revoked declined expired invitations cannot activate',()=>{for(const status of ['revoked','declined','expired']){let s=setup(),i=invite(s);i.status=status;s.currentAccountId=S.accounts[1].id;assert.throws(()=>S.accept(s,i.id));}let s=setup(),i=invite(s);i.expiresAt='2000-01-01';assert.throws(()=>accept(s,i));assert.equal(i.status,'expired');});
test('Agent, Admin without Manager and scope-outside Manager cannot read',()=>{let s=setup(),i=invite(s);accept(s,i);assert.equal(S.visible(s).length,0);const owner=s.members[0];owner.access='Admin';owner.role='Agent';assert.equal(view(s).length,0);owner.role='Manager';owner.scopes=[];assert.equal(view(s).length,0);owner.scopes=[{unitId:'other',includeSubUnits:true}];assert.equal(view(s).length,0);});
test('parent include subunits applies dynamically, direct-only excludes children',()=>{let s=setup(),i=invite(s);accept(s,i);s.members[0].scopes[0].includeSubUnits=false;assert.equal(view(s).length,0);s.members[0].scopes[0].includeSubUnits=true;assert.equal(view(s).length,3);s.members.find(m=>m.accountId===S.accounts[1].id).unitId='other';assert.equal(view(s).length,0);});
test('leave/remove terminate consent and preserve records; rejoin requires fresh acceptance',()=>{for(const reason of ['left','removed']){let s=setup(),i=invite(s),m=accept(s,i),count=s.business.length;S.terminate(s,m.id,reason);assert.equal(view(s).length,0);assert.equal(s.business.length,count);assert.ok(s.grants.find(g=>g.memberId===m.id).terminatedAt);s.currentAccountId=m.accountId;S.accept(s,i.id);assert.equal(s.members.length,1);const next=invite(s);assert.equal(view(s).length,0);const newMember=accept(s,next);assert.notEqual(newMember.id,m.id);assert.equal(view(s).length,3);}});
test('scope and sharing revocation remove list/detail/count/summary source',()=>{let s=setup(),m=accept(s,invite(s));s.members[0].scopes=[];assert.equal(view(s).length,0);s.members[0].scopes=[{unitId:'org',includeSubUnits:true}];S.grant(s,m).active=false;assert.equal(view(s).length,0);});
test('old direct members migrate pending without fabricated consent; Owner confirms',()=>{let s=setup();s.version=1;s.grants=[];s.members.push({id:'legacy',name:'Ahmed',email:S.accounts[1].email,access:'Member',role:'Agent',unitId:'team',scopes:[]});s=S.migrate(s);assert.equal(s.members.length,1);assert.equal(s.invites[0].status,'pending');assert.ok(!s.invites[0].acceptedAt);assert.equal(s.grants.length,0);assert.equal(view(s).length,0);S.consent(s,s.members[0]);accept(s,s.invites[0]);assert.equal(view(s).length,3);});
test('refresh serialization retains valid consent and invitation states',()=>{let s=setup();accept(s,invite(s));let restored=S.migrate(JSON.parse(JSON.stringify(s)));assert.equal(view(restored).length,3);assert.equal(restored.invites[0].status,'accepted');});
test('single organization constraint and protected Owner',()=>{let s=setup(),i=invite(s);s.grants.push({accountId:S.accounts[1].id,organizationId:'elsewhere',active:true});assert.throws(()=>accept(s,i));assert.throws(()=>S.terminate(s,'owner','left'));});
test('excluded/private and non-reshareable records never appear',()=>{let s=setup();accept(s,invite(s));s.business.push({id:'private',type:'chat',shareable:true,accountId:S.accounts[1].id},{id:'restricted',type:'lead',shareable:false,accountId:S.accounts[1].id});assert.equal(view(s).length,3);});
test('unknown-email invite has no member until that simulated account accepts',()=>{let s=setup(),i=invite(s,'new@example.test');assert.equal(view(s).length,0);assert.equal(s.members.length,1);s.accounts.push({id:S.accountId(i.email),email:i.email,name:i.email});accept(s,i);assert.equal(s.members.length,2);});
